#!/bin/bash

## Play the previous song in the playlist
previous_song() {
	mpc prev && notify-send --expire-time=2000 "Now Playing" "<span color='#78b9c4'>$(~/.config/eww/scripts/music --artist)</span> \n$(~/.config/eww/scripts/music --song)"
}

## Play the next song in the playlist
next_song() {
	mpc next && notify-send --expire-time=2000 "Now Playing" "<span color='#78b9c4'>$(~/.config/eww/scripts/music --artist)</span> \n$(~/.config/eww/scripts/music --song)"
}

## Pause the song
pause() {
	mpc pause && notify-send --expire-time=1000 "MPD" "<span color='#f06969'>Paused!</span>"
}
## Unpause the song
unpause() {
	mpc play && notify-send --expire-time=1000 "MPD" "<span color='#91d65c'>Unpaused!</span>"
}

## Execute accordingly
if [[ "$1" == "--previous" ]]; then
	previous_song
elif [[ "$1" == "--next" ]]; then
	next_song
elif [[ "$1" == "--pause" ]]; then
	pause
elif [[ "$1" == "--unpause" ]]; then
	unpause
fi
