{
  imports = [
    ./pufferpanel.nix
    ./invidious.nix
    ./qbittorrent.nix
    ./vaultwarden.nix
    ./matrix.nix
    ./fireshare.nix
    ./uptime.nix
    ./homepage.nix
    ./postgres.nix
    ./linkwarden.nix
    ./miniflux.nix
    ./searxng.nix
    ./redlib.nix
    ./actual.nix
    ./paperless.nix
  ];
}
