[opener]
evince = [{ run = 'evince "$@"', orphan = true, for = "unix" }]
play = [
	{ run = 'celluloid "$@"', orphan = true, for = "unix" }
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" }
]
[open]
append_rules = [
  { name = "*.pdf", use = "evince" }
]
